name: Integration

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.16.x'

      - name: Build
        run: go build -v
