name: Integration

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: '1.17.x'

      - name: Build
        run: go build -v
