name: Quality

on: [push, pull_request]

jobs:
  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: GolangCI
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.43
