name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: '1.17.x'

      - name: Publish Changelog
        uses: release-drafter/release-drafter@v5.15.0
        with:
          publish: true
          name: ${{ github.ref_name }}
          tag: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Releases
        uses: goreleaser/goreleaser-action@v2.9.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
